app_1/urls.py
"""Схемы для модели app_1"""

from django.urls import path
from . import views

app_name = 'app_1'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('topics/', views.topics, name='topics'),
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # новый топик
    path('new_topic/', views.new_topic, name='new_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
]

product_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_1.urls'))
]

app_1/models.py
from django.db import models

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Emtry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

app_1/forms.py
from django import forms
from app_1.models import Topic, Emtry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': 'Писать сюда!'}


class EmtryForm(forms.ModelForm):
    class Meta:
        model = Emtry
        fields = ['text']
        labels = {'text': 'Создать статью:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

app_1/views.py
from django.shortcuts import render
from app_1.models import Topic, Emtry
from django.shortcuts import render, redirect
from app_1.forms import TopicForm, EmtryForm


def index(request):
    return render(request, 'app_1/index.html')


def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.order_by('date_add')
    context = {'topics': topics}
    return render(request, 'app_1/topics.html', context)


def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
    entries = Emtry.objects.filter(topic_id=topic_id)
    context = {'topic': topic, "entries": entries}
    return render(request, 'app_1/topic.html', context)


def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('app_1:topics')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'app_1/new_topic.html', context)


def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    #topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EmtryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EmtryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save()
            new_entry.topic_id = topic_id
            new_entry.save()
            return redirect('app_1:topic', topic_id=topic_id)
    # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form}
    return render(request, 'app_1/new_entry.html', context)

app_1/templates/app_1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Приложение app_1</title>
</head>
<body>
<p>
    <a href="{% url 'app_1:index' %}">APP_1</a> -
    <a href="{% url 'app_1:topics' %}">TOPICS</a>
</p>


 {% block content %}{% endblock content %}
</body>
</html>

app_1/templates/app_1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Приложение app_1</title>
</head>
<body>
{% extends "app_1/base.html" %}


</body>
</html>

app_1/templates/app_1/new_entry.html
{% extends "app_1/base.html" %}

{% block content %}
<p>Добавить новую статью!</p>
   <form action="{% url 'app_1:new_topic' %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name="submit">Добавить статью</button>
 </form>

 {% endblock content %}

app_1/templates/app_1/new_topic.html
{% extends "app_1/base.html" %}

{% block content %}
<p>Добавить новую тему!</p>
   <form action="{% url 'app_1:new_topic' %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name="submit">Новая тема</button>
 </form>

 {% endblock content %}

app_1/templates/app_1/topic.html
{% extends "app_1/base.html" %}

{% block content %}
<p>Topic: {{ topic }}</p>
<p>Entries:</p>
<ul>
  {% for entry in entries %}

    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
       <p> <u>{{ entry.text |linebreaks}}</u></p>
    </li>

  {% empty %}
    <li>Нет записей по этой теме!!!</li>
  {% endfor %}
</ul>
<p>
  <a href="{% url 'app_1:new_entry' topic.id %}">Добавить статью</a>
</p>

{% endblock content %}

app_1/templates/app_1/topics.html
{% extends "app_1/base.html" %}

{% block content %}
<p>Topics</p>
  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'app_1:topic' topic.id %}">{{topic}}</a>
      </li>
    {% empty %}
      <li>Тема еще не создана</li>
    {% endfor %}
  </ul>

<a href="{% url 'app_1:new_topic' %}">Добавить новую тему:</a>

{% endblock content %}